services:
  backend:
    build:
      context: ./backend
    container_name: dpb_backend
    volumes:
      - ./backend:/app
    environment:
      PHONEBOOK_DB: ${PHONEBOOK_DB}
      PHONEBOOK_DB_USER: ${PHONEBOOK_DB_USER}
      PHONEBOOK_DB_PASSWORD: ${PHONEBOOK_DB_PASSWORD}
      LLM_URL: http://llm:11434
    depends_on:
      db:
        condition: service_healthy
      llm:
        condition: service_healthy
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: dpb_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: always

  nginx:
    image: nginx:alpine
    container_name: dpb_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
    restart: always

  db:
    image: postgres:18-alpine
    container_name: dpb_db
    environment:
      POSTGRES_DB: ${PHONEBOOK_DB}
      POSTGRES_USER: ${PHONEBOOK_DB_USER}
      POSTGRES_PASSWORD: ${PHONEBOOK_DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

  llm:
    build: llm
    container_name: dpb_llm
    volumes:
      - ollama_data:/root/.ollama
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "ollama --version || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  ollama_data:
